export const colors = {
    green: '#08DBA5',
    black: 'black',
    white: 'white',
    grey: 'grey',
    mainBackground: '#0F2635',
    rgba: 'rgba(0, 72, 82, 0.6)',
};
export const titles = {
    HEADER: 'СБРОСИТЬ ВЕС',
    HEADER_TITLE_1: 'Разминка',
    HEADER_TITLE_2: 'Общие настройки',
    HEADER_TITLE_3: 'Голосовые Опции',
    HEADER_TITLE_4: 'Поддержите нас',
    HEADER_SUB_TITLE_ONE: 'НЕДЕЛЯ 1',
    HEADER_SUB_TITLE_TWO: 'НЕДЕЛЯ 2',
    HEADER_SUB_TITLE_THREE: 'НЕДЕЛЯ 3',
    HEADER_SUB_TITLE_FOUR: 'НЕДЕЛЯ 4',
    HEADER_SUB_TITLE_FIVE: 'НЕДЕЛЯ 5',
    TEXT_1: '1 - й День',
    TEXT_2: '2 - й День',
    TEXT_3: '3 - й День',
    TEXT_4: '4 - й День',
    TEXT_5: '5 - й День',
    TEXT_6: '6 - й День',
    TEXT_7: '7 - й День',
    TEXT_8: '8 - й День',
    I_AM: 'Я',
    REPORT: 'Отчёт',
    PLAN: 'План',
    TITLE1: 'Новичёк',
    TITLE2: 'Продолжающий',
    TITLE3: 'Продвинутый',
    OPTIONS1: '5-10 минут в день',
    OPTIONS2: '10-20 минут в день',
    OPTIONS3: '15-30 минут в день',
    CHOOSE_PLAN: 'Выберите Свой План',
    TRAINING_PLAN: 'Худейте с оптимальным планом тренировок',
    NEXT_BUTTON: 'Cледующие',
    TITLE4: 'Я в порядке',
    TITLE5: 'Без прыжков',
    TITLE6: 'Малая ударная нагрузка',
    CHOOSE_PLAN1: 'У вас есть проблемы с коленями?',
    TRAINING_PLAN1: 'Выберите тренировку по своему состоянию',
    ENTER: 'Вход',
    REGISTRATION: 'Регистрация',
    REGISTER_HEADER1: 'Сколько Вы можете \n простоять в планке?',
    REGISTER_HEADER2: 'Ваши данные помогут нам сделать ваши \n \t\t\t\t\t тренировки эффективнее',
    REGISTER_HEADER3: 'Сколько раз Вы можете отжаться?',
    LOGIN: 'Вход',
    USERNAME: 'Имя пользователя',
    PASSWORD: 'Пароль',
    CONFIRM_PASSWORD: 'Подтвердите пароль',
    AUTHORIZATION: 'Авторизация',
    PASSWORD_DO_NOT_MATCH: 'Пароли не совпадают',
    REGISTER_ALERT: 'Введите данные',
    PASSWORD_ERROR: 'Не верный пароль или имя пользователя',
    TITLE_1: 'Напоминание',
    TITLE_2: 'Обратный отсчёт',
    TITLE_3: 'Отдых при тренировке',
    TITLE_4: 'Настройки звука',
    TITLE_5: 'Синхронизация с приложением Google',
    TITLE_6: 'Данные о здоровье',
    TITLE_7: 'Метрические единици измерения',
    TITLE_8: 'Выбор Языка',
    TITLE_9: 'Сбросить результаты',
    TITLE_10: 'Тест речи',
    TITLE_11: 'Выбрать синтезатор речи TTS',
    TITLE_12: 'Скачать синтезатор речи TTS',
    TITLE_13: 'Голос язык',
    TITLE_14: 'Скачать больше синтезаторов речи',
    TITLE_15: 'TTS Настройки устройства',
    TITLE_16: 'Поделиться с друзьями',
    TITLE_17: 'Оцените нас',
    TITLE_18: 'Отзыв',
    TITLE_19: 'Политика конфиденциальности',
    REPORT_HEADER_1: 'Всего',
    REPORT_HEADER_2: 'История',
    REPORT_HEADER_3: 'Вес',
    TRENING: 'Тренировки',
    CALORIES: 'Ккалории',
    CURRENT: 'Текущий',
    THE_HEAVIEST: 'Самый тяжёлый',
    THE_EASIEST: 'Самый лёгкий',
    BMI: 'ИМТ(кг/м²)',
    HEIGHT: 'Рост',
    EDIT: 'Редактировать',
    DURATION: 'Длительность',
};
export const ROUTERS = {
    SplashScreen: 'SplashScreen',
    MainScreen: 'MainScreen',
    RegisterScreen: 'RegisterScreen',
    RegisterScreen1: 'RegisterScreen1',
    RegisterScreen2: 'RegisterScreen2',
    RegisterScreen3: 'RegisterScreen3',
    RegisterScreen4: 'RegisterScreen4',
    ReportScreen: 'ReportScreen',
    ProfileScreen: 'ProfileScreen',
    SignUp: 'SignUp',
};